apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    run: eureka-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    run: eureka-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    run: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eureka-server
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: soedomoto/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"