apiVersion: v1
kind: Service
metadata:
  name: hystrix-dashboard
  labels:
    run: hystrix
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    run: hystrix
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hystrix
  labels:
    run: hystrix
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hystrix
  template:
    metadata:
      labels:
        run: hystrix
    spec:
      containers:
        - name: hystrix
          image: soedomoto/hystrix:latest
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_URL
              value: "http://eureka:admin@eureka-server:8761/eureka"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"